{% set name = "whitebox" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b66a4f0bce62529adca70cfa96a81fe7ba6b000e5bf20f807f22616441c258a2

build:
  number: 0
  entry_points:
    - whitebox=whitebox.cli:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - click >=6.0
    - pip
    - python >=3.6
    - setuptools
  run:
    - click >=6.0
    - python >=3.6
    - setuptools

test:
  imports:
    - os

about:
  home: https://github.com/giswqs/whitebox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An advanced geospatial data analysis platform
  doc_url: https://whitebox.readthedocs.io
  dev_url: https://github.com/giswqs/whitebox

extra:
  recipe-maintainers:
    - giswqs
