travis:
  secure:
    BINSTAR_TOKEN: io7RndSCNy8qoZBqBttFNEDsCo2MX6SGgeVGuzVvSBQ3aVraCAWoaXdG8t3Ev3hVDEgRZsOYJuPUos/1Wv2l9652Y8ZMf6ARmT2KTqo/jaU6rXrfkIt7nByBAmLD2GN3XxU00Oz+/OmJAnR0jZLDQHmvRObWRPiLzY3wbFsVr0DiUeo2WogKQZ/D/JGBreTLTQiAu9mk81uPTOODjBZAUG1AEk7SJqg5b+LvC4TGadVMXkr+6fqeulLJVpLOrgpSIxHgsVsVC6ZxyYGuogqukM5ggVFOke1OeXlWEt39cwYVxc8qSQQNaxWXkdl6yjz8x/3pnbpITGqXYqZNNrBVJHkJQFREIQ2/AQeWDsRuFjEAOfVY8oi3ARE0M/EqrzkBQ1ZLsOI1KtFdMFDKBZdB7gkcxaWWzgsLp+WYU/ZCiRryt0ACxyDRVpl61+gvE118kqdPM84JHnaWIJvciZ0hKjxTDR/9pK3/T2SPhqmZLMinkJEOvo8LGhNB76baxLIPYDAw6WUGi41lF77uPIvvRSwcDA/qYqw7M5cLJRMp0JpgPvUyuiEkaIbN4fmjTKespbZDk9hLmXBkaAE+StKQzjKJBJzmQEW2NV7Qz9+vzT0gMajGm7Tg3MSIthFocMDIsyNVijZCEpHySRPyOS1nLKKnOalWGLkfao16fzWA0xI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
